const fs = require('fs');
const path = require('path');
const { dateInTimeZone } = require('./util');

function generateTonightHTML(events) {
  const today = dateInTimeZone();
  const todayDate = new Date(today + 'T12:00:00');
  const dow = todayDate.getDay();

  const tonight = events.filter(e => e.date === today).sort((a, b) => (b.for_you_score || 0) - (a.for_you_score || 0));

  const fri = new Date(todayDate);
  fri.setDate(todayDate.getDate() + ((5 - dow + 7) % 7));
  const sun = new Date(fri);
  sun.setDate(fri.getDate() + 2);
  const wkStart = (dow >= 5 || dow === 0) ? today : fri.toISOString().slice(0, 10);
  const wkEnd = sun.toISOString().slice(0, 10);
  const weekend = events.filter(e => e.date && e.date >= wkStart && e.date <= wkEnd && e.date !== today)
    .sort((a, b) => (b.for_you_score || 0) - (a.for_you_score || 0));

  const cutoff = new Date(Date.now() - 48 * 3600000).toISOString();
  const newDrops = events.filter(e => e.first_seen && e.first_seen >= cutoff)
    .sort((a, b) => new Date(b.first_seen) - new Date(a.first_seen));

  const network = events.filter(e => e.my_network_match)
    .sort((a, b) => (a.date || '~').localeCompare(b.date || '~'));

  // Hard Summer countdown
  const HARD_SUMMER_DATE = '2026-08-01';
  const hsEvents = events.filter(e => e.festival_name === 'Hard Summer');
  const hsDaysUntil = Math.ceil((new Date(HARD_SUMMER_DATE + 'T12:00:00') - todayDate) / 86400000);

  const fmtDate = (d) => {
    if (!d) return '';
    const dt = new Date(d + 'T12:00:00');
    return dt.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' });
  };

  function esc(s) { return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;'); }

  function eventRow(e) {
    const net = e.my_network_match ? ' 🔗' : '';
    const ug = e.is_underground ? ' [ug]' : '';
    const time = e.start_time ? ` ${esc(e.start_time)}` : '';
    const price = e.price ? ` — ${esc(e.price)}` : '';
    const age = e.age ? ` ${esc(e.age)}` : '';
    const link = (e.ticket_url || e.source_url || '').trim();
    const title = link ? `<a href="${esc(link)}">${esc(e.title)}</a>` : esc(e.title);
    return `<div class="row">${esc(fmtDate(e.date))}${time} · ${title} @ ${esc(e.venue || 'TBA')}${price}${age}${ug}${net}</div>`;
  }

  function section(title, items, max) {
    if (!items.length) return '';
    const rows = items.slice(0, max || 50).map(eventRow).join('\n');
    return `<h2>${esc(title)} <span class="count">(${items.length})</span></h2>\n${rows}`;
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tonight in LA — ${fmtDate(today)}</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{background:#0c0c0d;color:#e8e8e8;font:13px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;padding:12px 16px;max-width:800px;margin:0 auto}
h1{font-size:16px;letter-spacing:.5px;border-bottom:1px solid #333;padding-bottom:8px;margin-bottom:12px}
h1 span{color:#9a9a9a;font-weight:400;font-size:12px}
h2{font-size:13px;color:#c98bff;margin:16px 0 6px;text-transform:uppercase;letter-spacing:.5px}
h2 .count{color:#9a9a9a;font-weight:400}
.row{padding:3px 0;border-bottom:1px solid #1a1a1c;color:#ccc;font-size:12px}
.row a{color:#7aa2ff;text-decoration:none}
.row a:hover{text-decoration:underline}
.footer{margin-top:20px;padding-top:8px;border-top:1px solid #333;color:#666;font-size:11px}
</style>
</head>
<body>
<h1>TONIGHT IN LA <span>${esc(fmtDate(today))} · generated ${new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })}</span></h1>
${section('TONIGHT', tonight, 30)}
${section('THIS WEEKEND', weekend, 40)}
${section('NEW DROPS', newDrops, 25)}
${section('MY NETWORK', network, 20)}
${hsDaysUntil > 0 ? `<h2 style="color:#6fa8ff">HARD SUMMER COUNTDOWN</h2>\n<div class="row" style="color:#6fa8ff;font-weight:600">${hsDaysUntil} days until Hard Summer (Aug 1–2)${hsEvents.length ? ` — ${hsEvents.length} events in lineup` : ''}</div>${hsEvents.length ? '\n' + hsEvents.map(eventRow).join('\n') : ''}` : ''}
<div class="footer">Generated by SoCal Event Radar · ${events.length} events tracked</div>
</body>
</html>`;

  const outPath = path.join(__dirname, '..', 'public', 'tonight.html');
  fs.writeFileSync(outPath, html);
  console.log(`  digest: tonight.html (${tonight.length} tonight, ${weekend.length} weekend, ${newDrops.length} new, ${network.length} network)`);
}

module.exports = { generateTonightHTML };
